#!/bin/sh
#
# Usage:
#
#    cd to a work directory (sandbox) or to a package in one of those and
# execute, 'lwcRelease.'  In the former case, ALL packages in the work directory
# will be marked for lightweight code release.  In the latter, just the package
# itself.
#
#
# BUGS:
#   o  this is a simple script that hides how we choose to flag stuff intended for
#      lightweight code release.
#
#   o  we assume that the packages are checkouts of all files in them
#

cvs tag -F lwc